// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emmzymigdfdipajgnzht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtbXp5bWlnZGZkaXBhamduemh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTc1NjQsImV4cCI6MjA1ODgzMzU2NH0.I1sHdfmjAtEQX7hoiN3IWCIlK1HKaf75KyQuDknhD7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);